export const GUARD_LOGIN_REQUEST = "GUARD_LOGIN_REQUEST";
export const GUARD_LOGIN_SUCCESS = "GUARD_LOGIN_SUCCESS";
export const GUARD_LOGIN_FAIL = "GUARD_LOGIN_FAIL";
export const GUARD_LOGOUT = "GUARD_LOGOUT";


export const GUARD_REGISTER_REQUEST  = "GUARD_REGISTER_REQUEST";
export const GUARD_REGISTER_SUCCESS  = "GUARD_REGISTER_SUCCESS";
export const GUARD_REGISTER_FAIL  = "GUARD_REGISTER_FAIL";

