export const GUARD_LOGIN_REQUEST = "GUARD_LOGIN_REQUEST";
export const GUARD_LOGIN_SUCCESS = "GUARD_LOGIN_SUCCESS";
export const GUARD_LOGIN_FAIL = "GUARD_LOGIN_FAIL";
export const GUARD_LOGOUT = "GUARD_LOGOUT";
